version: "3.8"
services:
  front:
    image: lorena612/front-coandco:v1
    ports:
      - "5000:5000"
    networks:
      - frontn
    depends_on:
      - initdb
    environment:
      - DB_HOST=database-1.c9yjy3nmd8az.us-east-1.rds.amazonaws.com
      - DB_USER=proyectocoandco
      - DB_PASSWORD=hola1234
      - DB_NAME=coandco
      - API_URL=https://n0g86wyeq5.execute-api.us-east-1.amazonaws.com/app
      
  initdb:
    image: lorena612/bd-coandco:v1
    networks:
      - frontn

networks:
  frontn:

