version: "3.8"
services:
  front:
    build: ./
    ports:
      - "5000:5000"
    networks:
      - frontn
    depends_on:
      - initdb
    environment:
      - DB_HOST=database-1.c9yjy3nmd8az.us-east-1.rds.amazonaws.com
      - DB_USER=proyectocoandco
      - DB_PASSWORD=hola1234
      - DB_NAME=coandco
      
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    networks:
      - frontn
    depends_on:
      - initdb
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database-1.c9yjy3nmd8az.us-east-1.rds.amazonaws.com
      - PMA_USER=proyectocoandco
      - PMA_PASSWORD=hola1234
      
  initdb:
    image: alpine:latest
    command: ["sh", "-c", "apk add --no-cache mysql-client && mysql -h database-1.c9yjy3nmd8az.us-east-1.rds.amazonaws.com -u proyectocoandco -phola1234 < /docker-entrypoint-initdb.d/co-co.sql"]
    volumes:
      - ./basededatos/co-co.sql:/docker-entrypoint-initdb.d/co-co.sql
    networks:
      - frontn

networks:
  frontn:

