version: "3.8"
services:
  front:
    build: ./
    ports:
      - "5000:5000"
    networks:
      - frontn
      
  myphp:
    image: phpmyadmin:latest
    restart: always
    ports:
      -"8080:8080"
    networks:
      - frontn
    environment:
      - PMA_ARBITRARY=1

volumes:
  dbsql:
    name: dbsql

networks:
  frontn: