apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: initdb
  name: initdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: initdb
  template:
    metadata:
      labels:
        app: initdb
    spec:
      containers:
      - image: lorena612/bd-coandco:v1
        name: initdb
        env:
        - name: HOST
          value: database-1.c9yjy3nmd8az.us-east-1.rds.amazonaws.com
        - name: USER
          value: proyectocoandco
        - name: PASSWORD
          value: hola1234