apiVersion: v1
kind: Service
metadata:
  labels:
    app: front
  name: front
spec:
  type: LoadBalancer
  ports:
  - name: "front-service"
    port: 5000
    targetPort: 5000
    nodePort: 31000
  selector:
    app: front